<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <AssemblyName>Breach.API</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Breach</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="AxiomVerge" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AxiomVerge">
      <HintPath>..\..\libs\AxiomVerge.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FNA">
      <HintPath>..\..\libs\FNA.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MMHOOK_AxiomVerge">
      <HintPath>..\..\libs\MMHOOK_AxiomVerge.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" Version="4.2.0" />
    <!-- Keep the same as patch assembly -->
    <PackageReference Include="MonoMod.RuntimeDetour" Version="22.7.31.1" />
  </ItemGroup>

</Project>