<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <AssemblyName>AxiomVerge.Breach.mm</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="AxiomVerge" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AxiomVerge">
      <HintPath>..\..\libs\AxiomVerge.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="FNA">
      <HintPath>..\..\libs\FNA.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API\Breach.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Keep the same as API assembly -->
    <PackageReference Include="MonoMod.RuntimeDetour" Version="22.7.31.1">
      <ExcludeAssets>none</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>